spring:
  mvc:
    problemdetails:
      enabled: true

  data:
    mongodb:
      url: mongodb://root:PKxApOO7dAg6SddEGxbjdKJx62V-VxxFWKjgo7Cdv1yygVsS@12f1c777-cf7c-45fb-9cdf-479d15d2ff10.asia-southeast1.firestore.goog:443/mongodb-db-job-order?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false
#      host: localhost
#      port: 13500
#      database: logistic
#      username: root
#      password: mongodb
#      authentication-database: admin

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}