spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/job
                - Path=/api/v1/job/**

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers
                - Path=/api/v1/customers/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
server:
  port: 7000

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/